# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rechange.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_change(object):
    def setupUi(self, change):
        change.setWindowTitle("myda")
        change.setObjectName("change")
        change.resize(301, 329)
        self.line = QtWidgets.QFrame(change)
        self.line.setGeometry(QtCore.QRect(10, 140, 281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.python_lab = QtWidgets.QLabel(change)
        self.python_lab.setGeometry(QtCore.QRect(10, 160, 401, 16))
        self.python_lab.setObjectName("python_lab")
        self.java_groupBox = QtWidgets.QGroupBox(change)
        self.java_groupBox.setGeometry(QtCore.QRect(10, 60, 131, 71))
        self.java_groupBox.setTitle("")
        self.java_groupBox.setObjectName("java_groupBox")
        self.radioButton_java_2 = QtWidgets.QRadioButton(self.java_groupBox)
        self.radioButton_java_2.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.radioButton_java_2.setObjectName("radioButton_java_2")
        self.radioButton_java_1 = QtWidgets.QRadioButton(self.java_groupBox)
        self.radioButton_java_1.setGeometry(QtCore.QRect(10, 10, 89, 16))
        self.radioButton_java_1.setChecked(True)
        self.radioButton_java_1.setAutoRepeat(False)
        self.radioButton_java_1.setObjectName("radioButton_java_1")
        self.java_pushButton = QtWidgets.QPushButton(change)
        self.java_pushButton.setGeometry(QtCore.QRect(190, 100, 75, 23))
        self.java_pushButton.setObjectName("java_pushButton")
        self.java_lab = QtWidgets.QLabel(change)
        self.java_lab.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.java_lab.setBaseSize(QtCore.QSize(0, 0))
        self.java_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.java_lab.setObjectName("java_lab")
        self.line_2 = QtWidgets.QFrame(change)
        self.line_2.setGeometry(QtCore.QRect(10, 300, 281, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.java_path_show = QtWidgets.QLabel(change)
        self.java_path_show.setGeometry(QtCore.QRect(40, 30, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.java_path_show.setFont(font)
        self.java_path_show.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.java_path_show.setTextFormat(QtCore.Qt.AutoText)
        self.java_path_show.setObjectName("java_path_show")
        self.python_groupBox__2 = QtWidgets.QGroupBox(change)
        self.python_groupBox__2.setGeometry(QtCore.QRect(10, 220, 131, 71))
        self.python_groupBox__2.setTitle("")
        self.python_groupBox__2.setObjectName("python_groupBox__2")
        self.radioButton_python_2 = QtWidgets.QRadioButton(self.python_groupBox__2)
        self.radioButton_python_2.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.radioButton_python_2.setObjectName("radioButton_python_2")
        self.radioButton_python_1 = QtWidgets.QRadioButton(self.python_groupBox__2)
        self.radioButton_python_1.setGeometry(QtCore.QRect(10, 10, 89, 16))
        self.radioButton_python_1.setChecked(True)
        self.radioButton_python_1.setAutoRepeat(False)
        self.radioButton_python_1.setObjectName("radioButton_python_1")
        self.python_path_shw = QtWidgets.QLabel(change)
        self.python_path_shw.setGeometry(QtCore.QRect(40, 180, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.python_path_shw.setFont(font)
        self.python_path_shw.setObjectName("python_path_shw")
        self.python_pushButton_3 = QtWidgets.QPushButton(change)
        self.python_pushButton_3.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.python_pushButton_3.setObjectName("python_pushButton_3")

        self.retranslateUi(change)
        QtCore.QMetaObject.connectSlotsByName(change)

    def retranslateUi(self, change):
        _translate = QtCore.QCoreApplication.translate
        change.setWindowTitle(_translate("change", "Dialog"))
        self.python_lab.setText(_translate("change", "当前 PYTHON_HOME"))
        self.radioButton_java_2.setText(_translate("change", "配置二"))
        self.radioButton_java_1.setText(_translate("change", "配置一"))
        self.java_pushButton.setText(_translate("change", "保存配置"))
        self.java_lab.setText(_translate("change", "当前 JAVA_HOME"))
        self.java_path_show.setText(_translate("change", "当前未设置"))
        self.radioButton_python_2.setText(_translate("change", "配置二"))
        self.radioButton_python_1.setText(_translate("change", "配置一"))
        self.python_path_shw.setText(_translate("change", "当前未设置"))
        self.python_pushButton_3.setText(_translate("change", "保存配置"))

